import os
import time

import jax
import jax.numpy as jnp
import numpy as np
from jax.tree_util import tree_map

import ml_collections
from absl import logging
import wandb

from jaxpi.samplers import UniformSampler, SpaceSampler
from jaxpi.logging import Logger
from jaxpi.utils import save_checkpoint, restore_checkpoint

from flax.jax_utils import replicate

import models
from utils import get_dataset
from scipy.io import loadmat


def _load_rollout_pool(max_additions: int, num_initial_ics: int,
                       num_vars: int, mat_path="data/train_rollouts.mat") -> jnp.ndarray:
    """
    Load pre-computed rollout ICs from a .mat file generated by
    generate_train_rollouts.py.
 
    Expected keys in the .mat file:
        u0_original      : (num_initial_ics, N)
        u0_rollout_1     : (num_initial_ics, N)
        ...
        u0_rollout_K     : (num_initial_ics, N)   K = max_additions
 
    Returns:
        u0_pool : (num_initial_ics * (max_additions + 1), N) — full pre-built
                  pool with original ICs in slot 0 and rollout ICs in slots 1…K.
    """
    data = loadmat(mat_path)
 
    total_pool_size = num_initial_ics * (max_additions + 1)
    u0_pool = np.zeros((total_pool_size, num_vars), dtype=np.float32)
 
    u0_pool[:num_initial_ics] = data["u0_original"].astype(np.float32)
 
    for addition in range(1, max_additions + 1):
        key = f"u0_rollout_{addition}"
        if key not in data:
            raise KeyError(
                f"Key '{key}' missing from {mat_path}. "
                f"Regenerate with max_additions >= {addition}."
            )
        slot_start = num_initial_ics * addition
        slot_end   = slot_start + num_initial_ics
        u0_pool[slot_start:slot_end] = data[key].astype(np.float32)
 
    logging.info(
        f"Loaded rollout pool from {mat_path}: "
        f"{max_additions + 1} slots × {num_initial_ics} ICs = {total_pool_size} rows."
    )
    return jnp.array(u0_pool)
 
 
def _expand_pool_model(
    u0_original: jnp.ndarray,
    u0_pool: jnp.ndarray,
    model_state,
    predict_batch,
    t_end_vec: jnp.ndarray,
    rollout_steps: int,
    additions_done: int,
    num_initial_ics: int,
    num_vars: int,
) -> jnp.ndarray:
    """
    Expand the IC pool by rolling out u0_original `rollout_steps` windows
    forward using the current network, then writing the result into the next
    free slot of u0_pool.
 
    Returns the updated u0_pool.
    """
    single_params = jax.device_get(
        tree_map(lambda x: x[0], model_state)
    ).params
 
    u_rolled = u0_original
    for _ in range(rollout_steps):
        u_rolled = predict_batch(single_params, u_rolled, t_end_vec)
        u_rolled = u_rolled.reshape(num_initial_ics, num_vars)
 
    slot_start = num_initial_ics * (additions_done + 1)
    slot_end   = slot_start + num_initial_ics
    u0_pool    = u0_pool.at[slot_start:slot_end].set(u_rolled)
    return u0_pool

 
# ---------------------------------------------------------------------------
# Main training loop
# ---------------------------------------------------------------------------
def train_and_evaluate(config, workdir: str):
 
    # ── W&B ────────────────────────────────────────────────────────────────
    wandb.init(project=config.wandb.project, name=config.wandb.name)
 
    # ── Reference data (used only for eval logging during training) ────────
    # Start with single window data
    x_ref_eval_all, u_ref_eval_all, t_star_all = get_dataset()
    u_ref_eval = u_ref_eval_all[0:5, :]        # shape (5, N)
    x_ref_eval = x_ref_eval_all[0:5, 0:50, :]   # shape (5, num_t, N)
    t_star = t_star_all[0:50]
    logging.info(f"###### Temporal: {u_ref_eval.shape}")

    # Parameters for l2 error computation
    trajs_per_window = 45
    idx_jump = 50
    time_steps = 50
 
    # ── Hyper-parameters ───────────────────────────────────────────────────
    num_vars        = 40
    num_initial_ics = config.training.get("num_initial_ics", 10000)
    max_additions   = config.training.get("max_additions",   5)
    update_interval = config.training.get("update_interval", 10000)
    batch_size      = config.training.batch_size_per_device
    seed            = config.training.get("seed", 42)
    
    # Augmentation scheme: "file" | "model"  (default: "file")
    augmentation_scheme = config.training.get("augmentation_scheme", "file")
    
    logging.info(f"Pool augmentation scheme: '{augmentation_scheme}'")

    # ── Sample the fixed original IC set ─────────────────────
    key = jax.random.PRNGKey(seed)
    mean_ic, std_ic = 6.0, 2.0
    u0_original = mean_ic + std_ic * jax.random.normal(
        key, shape=(num_initial_ics, num_vars)
    )  # shape (num_initial_ics, N) — kept fixed for all rollout augmentations
 
    logging.info(
        f"Sampled {num_initial_ics} original ICs from N({mean_ic}, {std_ic}²)."
    )
 
    # ── Pre-allocate the full IC pool ──────────────────────────────────────
    # Total size is known: num_initial_ics rows per addition, plus the original.
    total_pool_size = num_initial_ics * (max_additions + 1)
    u0_pool = jnp.zeros((total_pool_size, num_vars))
    # Write original ICs into slot 0
    u0_pool = u0_pool.at[:num_initial_ics].set(u0_original)
    active_size   = num_initial_ics          # number of valid rows right now
    additions_done = 0
 
    logging.info(
        f"Pre-allocated IC pool: {total_pool_size} rows "
        f"({max_additions + 1} slots × {num_initial_ics} ICs). "
        f"Active: {active_size}."
    )
    
    # ── IC pool initialisation ─────────────────────────────────────────────
    total_pool_size = num_initial_ics * (max_additions + 1)
 
    if augmentation_scheme == "file":
        # Load the full pre-computed pool from disk.  All slots are available
        # from step 0 — no progressive expansion needed.
        u0_pool    = _load_rollout_pool(
            max_additions, num_initial_ics, num_vars,
            "data/"+config.training.get("augmentation_file_name", "train_rollouts.mat")
        )
        active_size    = num_initial_ics
        additions_done = 0
 
    elif augmentation_scheme == "model":
        # Start with only the original ICs; expand progressively during training.
        u0_pool = jnp.zeros((total_pool_size, num_vars))
        u0_pool = u0_pool.at[:num_initial_ics].set(u0_original)
        active_size    = num_initial_ics
        additions_done = 0
 
    else:
        raise ValueError(
            f"Unknown augmentation_scheme '{augmentation_scheme}'. "
            f"Choose 'file' or 'model'."
        )
 
    logging.info(
        f"IC pool ready: total={total_pool_size}, active={active_size}."
    )

    # ── Samplers ───────────────────────────────────────────────────────────
    # t is sampled uniformly over the training window [t0, t1].
    dom_t     = jnp.array([[t_star[0], t_star[-1]]])
    sampler_t = UniformSampler(dom_t, batch_size)
 
    # IC sampler: samples rows uniformly at random from the active pool slice.
    # Rebuilt whenever active_size grows.
    sampler_u = SpaceSampler(u0_pool[:active_size], batch_size)
    res_sampler = zip(sampler_u, sampler_t)

    # ── Build model ────────────────────────────────────────────────────────
    model     = models.L96UDON(config, t_star)
    evaluator = models.L96UDONEvaluator(config, model)
 
    if config.saving.get("restore_checkpoint", False):
        ckpt_path   = os.path.join(os.getcwd(), config.saving.restore_checkpoint_path)
        model.state = restore_checkpoint(model.state, ckpt_path)
        model.state = replicate(model.state)
        logging.info(f"Restored and re-replicated checkpoint from: {ckpt_path}")
 
    # ── JIT-compiled batch prediction for pool expansion ───────────────────
    # vmap over ICs (axis 1), fix params and t.
    predict_batch = jax.jit(jax.vmap(model.x_net, in_axes=(None, 0, None)))
    # Trunk expects a 1-D time vector: shape (1,)
    t_end_vec = jnp.array([t_star[-1]])

    # Augment pool from beginning if restore_checkpoint
    # This assumes the restoration is done after all additional training data has been added
    if config.saving.get("restore_checkpoint", False):
        if (augmentation_scheme == "model"):
            for i in range(max_additions):
                rollout_steps = i + 1
        
                u0_pool = _expand_pool_model(
                    u0_original   = u0_original,
                    u0_pool       = u0_pool,
                    model_state   = model.state,
                    predict_batch = predict_batch,
                    t_end_vec     = t_end_vec,
                    rollout_steps = rollout_steps,
                    additions_done= i,
                    num_initial_ics = num_initial_ics,
                    num_vars      = num_vars,
                )

                expansion_msg = f"rollout ×{rollout_steps} window(s) via models"
                active_size = num_initial_ics * (rollout_steps + 1)
                logging.info(
                    f"Pool expansion #{i+1}: "
                    f"{expansion_msg} → active ICs {active_size}/{total_pool_size}"
                )
        elif (augmentation_scheme == "file"):
            for i in range(max_additions):
                expansion_msg = f"slot {i + 1} unlocked from archive"
                active_size = num_initial_ics * (i + 2)
                logging.info(
                    f"Pool expansion #{i+1}: "
                    f"{expansion_msg} → active ICs {active_size}/{total_pool_size}"
                )
        
        additions_done = max_additions
        active_size = num_initial_ics * (max_additions + 1)

        # Rebuild sampler over the enlarged active region.
        sampler_u   = SpaceSampler(u0_pool[:active_size], batch_size)
        res_sampler = zip(sampler_u, sampler_t)

        # Update trajectories used on l2 error plotting
        # 1. Dynamically build the list of indices
        eval_indices = []
        for k in range(max_additions + 1):
            start_idx = k * idx_jump
            eval_indices.extend(range(start_idx, start_idx + trajs_per_window))

        # 2. Extract the batched evaluation data using the generated indices
        u_ref_eval = u_ref_eval_all[eval_indices, :]
        x_ref_eval = x_ref_eval_all[eval_indices, 0:time_steps, :]
        t_star = t_star_all[0:time_steps]
            

    # ── Training loop ──────────────────────────────────────────────────────
    logger     = Logger()
    start_time = time.time()
    logging.info("Waiting for JIT compilation…")
 
    for step in range(config.training.max_steps):
 
        # ── Forward + gradient step ────────────────────────────────────────
        batch       = next(res_sampler)          # (batch_u, batch_t), each (devices, B, ·)
        model.state = model.step(model.state, batch)
 
        # ── Adaptive loss weighting (optional) ────────────────────────────
        if config.weighting.scheme in ("grad_norm", "ntk"):
            if step % config.weighting.update_every_steps == 0:
                model.state = model.update_weights(model.state, batch)
 
        # ── IC pool expansion ──────────────────────────────────────────────
        # Trigger: every update_interval steps, as long as budget remains.
        if (
            step > 0
            and step % update_interval == 0
            and additions_done < max_additions
        ):
            if (augmentation_scheme == "model"):
                rollout_steps = additions_done + 1
    
                u0_pool = _expand_pool_model(
                    u0_original   = u0_original,
                    u0_pool       = u0_pool,
                    model_state   = model.state,
                    predict_batch = predict_batch,
                    t_end_vec     = t_end_vec,
                    rollout_steps = rollout_steps,
                    additions_done= additions_done,
                    num_initial_ics = num_initial_ics,
                    num_vars      = num_vars,
                )
                expansion_msg = f"rollout ×{rollout_steps} window(s) via models"

            else:
                expansion_msg = f"slot {additions_done + 1} unlocked from archive"
            
            active_size = num_initial_ics * (additions_done + 2)

            # Rebuild sampler over the enlarged active region.
            sampler_u   = SpaceSampler(u0_pool[:active_size], batch_size)
            res_sampler = zip(sampler_u, sampler_t)
            additions_done += 1
 
            logging.info(
                f"Step {step:>7d} | Pool expansion #{additions_done}: "
                f"{expansion_msg} → active ICs {active_size}/{total_pool_size}"
            )

            # Update trajectories used on l2 error plotting
            # 1. Dynamically build the list of indices
            eval_indices = []
            for k in range(additions_done + 2):
                start_idx = k * idx_jump
                eval_indices.extend(range(start_idx, start_idx + trajs_per_window))

            # 2. Extract the batched evaluation data using the generated indices
            u_ref_eval = u_ref_eval_all[eval_indices, :]
            x_ref_eval = x_ref_eval_all[eval_indices, 0:time_steps, :]
            t_star = t_star_all[0:time_steps]
            logging.info(f"###### Temporal: shape: {u_ref_eval.shape}, current addit.:{additions_done+1}")
 
        # ── Logging ────────────────────────────────────────────────────────
        if jax.process_index() == 0:
            if step % config.logging.log_every_steps == 0:
                state    = jax.device_get(tree_map(lambda x: x[0], model.state))
                batch_dev = jax.device_get(tree_map(lambda x: x[0], batch))
 
                log_dict = evaluator(state, batch_dev, u_ref_eval, x_ref_eval)
 
                # Track pool coverage for visibility
                log_dict["pool/active_ics"]  = active_size
                log_dict["pool/additions"]   = additions_done
 
                wandb.log(log_dict, step)
 
                end_time = time.time()
                logger.log_iter(step, start_time, end_time, log_dict)
                start_time = end_time
 
        # ── Checkpointing ──────────────────────────────────────────────────
        if config.saving.save_every_steps is not None:
            if ((step + 1) % config.saving.save_every_steps == 0
                    or (step + 1) == config.training.max_steps):
                ckpt_path = os.path.join(
                    os.getcwd(), config.wandb.name, "ckpt", "udon_model"
                )
                save_checkpoint(
                    model.state, ckpt_path, keep=config.saving.num_keep_ckpts
                )
 
    return model